import Head from 'next/head'
import { FormEvent, useState } from 'react'
import { useAuth } from '../Contexts/AuthContext';
import styles from '../styles/Home.module.css'
import { withSSRGuest } from '../utils/withSSRGuest';

export default function Home() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const { isAuthenticated, signIn } = useAuth();

  const handleSubmit = async (event: FormEvent) => {
    event.preventDefault();
    const data = {
      email,
      password
    }
    await signIn(data)

  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <form onSubmit={handleSubmit} className={styles.container}>
        <input type="email" value={email} onChange={e => setEmail(e.target.value)} />
        <input type="password" value={password} onChange={e => setPassword(e.target.value)} />
        <button type="submit" >
          Entrar
        </button>
      </form>

    </>
  )
}
export const getServerSideProps = withSSRGuest(async (ctx) => {
  

  return {
    props: {

    }
  }
})